services:
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    ports:
      - 54321:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../sql:/sql
    restart: always
